version: "3.3"
services:
 api:
   container_name: pythonapp_container
   image: pythonapp_image:v2
   depends_on :
       - postgres
   ports:
    - "3000:3000"

 postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5431:5431"
    volumes :
      - db_data:/data:rw

volumes:
  db_data:

